//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRNPortal.UI.Resources.Views.ComplianceSchemeMemberLanding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ComplianceSchemeMemberLanding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComplianceSchemeMemberLanding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRNPortal.UI.Resources.Views.ComplianceSchemeMemberLanding.ComplianceSchemeMember" +
                            "Landing", typeof(ComplianceSchemeMemberLanding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string account_name_manager {
            get {
                return ResourceManager.GetString("account_name_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string behalf_of_responsible_for {
            get {
                return ResourceManager.GetString("behalf_of_responsible_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string change_or_remove_compliance_scheme {
            get {
                return ResourceManager.GetString("change_or_remove_compliance_scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string change_or_remove_compliance_scheme_link {
            get {
                return ResourceManager.GetString("change_or_remove_compliance_scheme_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string compliance_scheme_name {
            get {
                return ResourceManager.GetString("compliance_scheme_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string handling_packaging_recovery_notes__PRNs__and_packaging_export_recovery_notes__PERNs_ {
            get {
                return ResourceManager.GetString("handling_packaging_recovery_notes_(PRNs)_and_packaging_export_recovery_notes_(PER" +
                        "Ns)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string organisation_id {
            get {
                return ResourceManager.GetString("organisation_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string paying_fees_and_charges_to_the_environmental_regulator {
            get {
                return ResourceManager.GetString("paying_fees_and_charges_to_the_environmental_regulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string paying_fees_and_charges_to_the_scheme_administrator {
            get {
                return ResourceManager.GetString("paying_fees_and_charges_to_the_scheme_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string reporting_organisation_details_and_keeping_them_up_to_date {
            get {
                return ResourceManager.GetString("reporting_organisation_details_and_keeping_them_up_to_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string responsible_for {
            get {
                return ResourceManager.GetString("responsible_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string submitting_packaging_data_to_the_environmental_regulator {
            get {
                return ResourceManager.GetString("submitting_packaging_data_to_the_environmental_regulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string what_they_are_responsible_for {
            get {
                return ResourceManager.GetString("what_they_are_responsible_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string you_can {
            get {
                return ResourceManager.GetString("you_can", resourceCulture);
            }
        }
    }
}
