//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRNPortal.UI.Resources.Views.ReviewCompanyDetails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReviewCompanyDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReviewCompanyDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRNPortal.UI.Resources.Views.ReviewCompanyDetails.ReviewCompanyDetails", typeof(ReviewCompanyDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string check_files_and_resubmit {
            get {
                return ResourceManager.GetString("check_files_and_resubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string check_files_and_submit {
            get {
                return ResourceManager.GetString("check_files_and_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string date_submitted {
            get {
                return ResourceManager.GetString("date_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string date_uploaded {
            get {
                return ResourceManager.GetString("date_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string detail_regarding_the_latest_file_submitted {
            get {
                return ResourceManager.GetString("detail_regarding_the_latest_file_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string detail_regarding_the_latest_file_uploaded {
            get {
                return ResourceManager.GetString("detail_regarding_the_latest_file_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string file_name {
            get {
                return ResourceManager.GetString("file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string files_already_submitted {
            get {
                return ResourceManager.GetString("files_already_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string files_to_submit {
            get {
                return ResourceManager.GetString("files_to_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string files_uploaded {
            get {
                return ResourceManager.GetString("files_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string files_youve_uploaded {
            get {
                return ResourceManager.GetString("files_youve_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string get_an_authorised_person_to_submit_the_files {
            get {
                return ResourceManager.GetString("get_an_authorised_person_to_submit_the_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string go_to_your_account_homepage {
            get {
                return ResourceManager.GetString("go_to_your_account_homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string how_to_submit_your_files {
            get {
                return ResourceManager.GetString("how_to_submit_your_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string information_will_be_sent_to_the_environmental_regulator {
            get {
                return ResourceManager.GetString("information_will_be_sent_to_the_environmental_regulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string no_not_right_now {
            get {
                return ResourceManager.GetString("no_not_right_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string report_packaging_data {
            get {
                return ResourceManager.GetString("report-packaging-data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string resubmit_your_members_organisation_details {
            get {
                return ResourceManager.GetString("resubmit_your_members_organisation_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string review_compliance_scheme {
            get {
                return ResourceManager.GetString("review_compliance_scheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReviewCompanyDetails_ResponseErrorMessage {
            get {
                return ResourceManager.GetString("ReviewCompanyDetails.ResponseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ReviewCompanyDetails_ResponseErrorMessage_Producer {
            get {
                return ResourceManager.GetString("ReviewCompanyDetails.ResponseErrorMessage.Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string submit_your_members_organisation_details {
            get {
                return ResourceManager.GetString("submit_your_members_organisation_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string submit_your_organisation_details {
            get {
                return ResourceManager.GetString("submit_your_organisation_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string submitted_by {
            get {
                return ResourceManager.GetString("submitted_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string text_assistive_warning {
            get {
                return ResourceManager.GetString("text_assistive.warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string uploaded_by {
            get {
                return ResourceManager.GetString("uploaded_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string yes_resubmit {
            get {
                return ResourceManager.GetString("yes_resubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string yes_submit {
            get {
                return ResourceManager.GetString("yes_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string you_dont_have_permission_to_submit {
            get {
                return ResourceManager.GetString("you_dont_have_permission_to_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string your_org_may_face_enforcement_action_if_the_data_you_submit_is_inaccurate {
            get {
                return ResourceManager.GetString("your_org_may_face_enforcement_action_if_the_data_you_submit_is_inaccurate", resourceCulture);
            }
        }
    }
}
