//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRNPortal.UI.Resources.Views.UploadNewFileToSubmit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UploadNewFileToSubmit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadNewFileToSubmit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRNPortal.UI.Resources.Views.UploadNewFileToSubmit.UploadNewFileToSubmit", typeof(UploadNewFileToSubmit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string date_submitted {
            get {
                return ResourceManager.GetString("date_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string date_uploaded {
            get {
                return ResourceManager.GetString("date_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string file_already_submitted {
            get {
                return ResourceManager.GetString("file_already_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string file_already_uploaded {
            get {
                return ResourceManager.GetString("file_already_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string file_name {
            get {
                return ResourceManager.GetString("file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string re_upload_packaging_data {
            get {
                return ResourceManager.GetString("re_upload_packaging_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string someone_in_your_team_will_need_to_submit_the_file {
            get {
                return ResourceManager.GetString("someone_in_your_team_will_need_to_submit_the_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string someone_in_your_team_will_need_to_submit_this_information {
            get {
                return ResourceManager.GetString("someone_in_your_team_will_need_to_submit_this_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string submitted_by {
            get {
                return ResourceManager.GetString("submitted_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string upload_new_file {
            get {
                return ResourceManager.GetString("upload_new_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string upload_new_file_to_submit_to_environmental_regulator {
            get {
                return ResourceManager.GetString("upload_new_file_to_submit_to_environmental_regulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string uploaded_by {
            get {
                return ResourceManager.GetString("uploaded_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string you_already_submitted_a_file {
            get {
                return ResourceManager.GetString("you_already_submitted_a_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string you_already_submitted_a_file_you_also_have_a_file_saved {
            get {
                return ResourceManager.GetString("you_already_submitted_a_file_you_also_have_a_file_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string you_can_upload_this_information_again {
            get {
                return ResourceManager.GetString("you_can_upload_this_information_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string you_have_already_uploaded_your_members_packaging_data {
            get {
                return ResourceManager.GetString("you_have_already_uploaded_your_members_packaging_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string your_organisation_already_submitted_a_file {
            get {
                return ResourceManager.GetString("your_organisation_already_submitted_a_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string your_organisation_already_submitted_a_file_you_also_have_file_saved {
            get {
                return ResourceManager.GetString("your_organisation_already_submitted_a_file_you_also_have_file_saved", resourceCulture);
            }
        }
    }
}
