//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRNPortal.UI.Resources.Views.FileUploadSubmissionConfirmation {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUploadSubmissionConfirmation {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadSubmissionConfirmation() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PRNPortal.UI.Resources.Views.FileUploadSubmissionConfirmation.Fi" +
                            "leUploadSubmissionConfirmation", typeof(FileUploadSubmissionConfirmation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string packaging_data_submitted_to_the_environmental_regulator {
            get {
                return ResourceManager.GetString("packaging_data_submitted_to_the_environmental_regulator", resourceCulture);
            }
        }
        
        internal static string go_to_your_account_homepage {
            get {
                return ResourceManager.GetString("go_to_your_account_homepage", resourceCulture);
            }
        }
        
        internal static string print_this_page {
            get {
                return ResourceManager.GetString("print_this_page", resourceCulture);
            }
        }
        
        internal static string submitted_by_x_at_y_on_z {
            get {
                return ResourceManager.GetString("submitted_by_x_at_y_on_z", resourceCulture);
            }
        }
        
        internal static string they_will_contact_your_organisation_if_there_are_any_issues {
            get {
                return ResourceManager.GetString("they_will_contact_your_organisation_if_there_are_any_issues", resourceCulture);
            }
        }
        
        internal static string they_will_email_or_phone_your_organisation_if_there_are_any_issues {
            get {
                return ResourceManager.GetString("they_will_email_or_phone_your_organisation_if_there_are_any_issues", resourceCulture);
            }
        }
        
        internal static string the_environmental_regulator_will_review_the_packaging_data {
            get {
                return ResourceManager.GetString("the_environmental_regulator_will_review_the_packaging_data", resourceCulture);
            }
        }
        
        internal static string the_environmental_regulator_will_review_your_packaging_data {
            get {
                return ResourceManager.GetString("the_environmental_regulator_will_review_your_packaging_data", resourceCulture);
            }
        }
        
        internal static string what_happens_next {
            get {
                return ResourceManager.GetString("what_happens_next", resourceCulture);
            }
        }
        
        internal static string you_can_save_this_page_using_the_print_option_in_your_browser {
            get {
                return ResourceManager.GetString("you_can_save_this_page_using_the_print_option_in_your_browser", resourceCulture);
            }
        }
    }
}
