//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRNPortal.UI.Resources.Views.FileUploadSubLanding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUploadSubLanding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadSubLanding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PRNPortal.UI.Resources.Views.FileUploadSubLanding.FileUploadSubLanding", typeof(FileUploadSubLanding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string accepted_by_regulator {
            get {
                return ResourceManager.GetString("accepted_by_regulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string an_example_csv_file {
            get {
                return ResourceManager.GetString("an_example_csv_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string approved_by_regulator {
            get {
                return ResourceManager.GetString("approved_by_regulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string before_you_start {
            get {
                return ResourceManager.GetString("before_you_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string cannot_start_yet {
            get {
                return ResourceManager.GetString("cannot_start_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string check_if_you_need_to_resubmit_members_packaging_data {
            get {
                return ResourceManager.GetString("check_if_you_need_to_resubmit_members_packaging_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string check_if_you_need_to_resubmit_packaging_data {
            get {
                return ResourceManager.GetString("check_if_you_need_to_resubmit_packaging_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string check_if_you_need_to_update_member_s_packaging_data {
            get {
                return ResourceManager.GetString("check_if_you_need_to_update_member\'s_packaging_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string check_if_you_need_to_update_packaging_data {
            get {
                return ResourceManager.GetString("check_if_you_need_to_update_packaging_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string check_the_govuk_guidance {
            get {
                return ResourceManager.GetString("check_the_govuk_guidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string deadline {
            get {
                return ResourceManager.GetString("deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string file_uploaded {
            get {
                return ResourceManager.GetString("file_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string how_to_build_a_csv_file_to_report_your_packaging_data {
            get {
                return ResourceManager.GetString("how_to_build_a_csv_file_to_report_your_packaging_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string if_youve_missed_a_deadline {
            get {
                return ResourceManager.GetString("if_youve_missed_a_deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string if_youve_missed_a_deadline_to_submit {
            get {
                return ResourceManager.GetString("if_youve_missed_a_deadline_to_submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string large_organisations {
            get {
                return ResourceManager.GetString("large_organisations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string not_started {
            get {
                return ResourceManager.GetString("not_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string read_the_guidance_on {
            get {
                return ResourceManager.GetString("read_the_guidance_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string rejected_by_regulator {
            get {
                return ResourceManager.GetString("rejected_by_regulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string report_members_packaging_data_for {
            get {
                return ResourceManager.GetString("report_members_packaging_data_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string report_packaging_data {
            get {
                return ResourceManager.GetString("report_packaging_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string report_packaging_data_for {
            get {
                return ResourceManager.GetString("report_packaging_data_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string resubmit_members_packaging_data {
            get {
                return ResourceManager.GetString("resubmit_members_packaging_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string resubmit_packaging_data {
            get {
                return ResourceManager.GetString("resubmit_packaging_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string start_now {
            get {
                return ResourceManager.GetString("start_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string status_unknown {
            get {
                return ResourceManager.GetString("status_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string submitted_to_regulator {
            get {
                return ResourceManager.GetString("submitted_to_regulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string update_members_packaging_data_basic {
            get {
                return ResourceManager.GetString("update_members_packaging_data_basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string update_packaging_data_basic {
            get {
                return ResourceManager.GetString("update_packaging_data_basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string view_submission_history {
            get {
                return ResourceManager.GetString("view_submission_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string view_your_packaging_data_files {
            get {
                return ResourceManager.GetString("view_your_packaging_data_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string what_packaging_data_you_need_to_collect {
            get {
                return ResourceManager.GetString("what_packaging_data_you_need_to_collect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string your_history {
            get {
                return ResourceManager.GetString("your_history", resourceCulture);
            }
        }
    }
}
