//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRNPortal.UI.Resources.Views.Application {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Declaration {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Declaration() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PRNPortal.UI.Resources.Views.Application.Declaration", typeof(Declaration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string confirm_declaration {
            get {
                return ResourceManager.GetString("confirm_declaration", resourceCulture);
            }
        }
        
        internal static string declaration_statement {
            get {
                return ResourceManager.GetString("declaration_statement", resourceCulture);
            }
        }
        
        internal static string declaration_warning {
            get {
                return ResourceManager.GetString("declaration_warning", resourceCulture);
            }
        }
        
        internal static string authorised_question {
            get {
                return ResourceManager.GetString("authorised_question", resourceCulture);
            }
        }
        
        internal static string authorised_reasons {
            get {
                return ResourceManager.GetString("authorised_reasons", resourceCulture);
            }
        }
        
        internal static string authorised_reason_1 {
            get {
                return ResourceManager.GetString("authorised_reason_1", resourceCulture);
            }
        }
        
        internal static string authorised_reason_2 {
            get {
                return ResourceManager.GetString("authorised_reason_2", resourceCulture);
            }
        }
        
        internal static string authorised_reason_3 {
            get {
                return ResourceManager.GetString("authorised_reason_3", resourceCulture);
            }
        }
        
        internal static string declaration {
            get {
                return ResourceManager.GetString("declaration", resourceCulture);
            }
        }
    }
}
