trigger: none
pr: none
pool: DEFRA-COMMON-ubuntu2004-SSV3

parameters:
- name: teamName
  displayName: 'Select Team Name:    (works only with "development" as target env)'
  default: 'Team-1_Pi'
  type: string
  values:
    - Team-1_Pi
    - Team-2_Wastebusters
    - Team-3_Recyclers
    - Team-4_QA
    - Team-5_Phoenix
    - Team-6_Stig
    - Team-7_Oscar
    - Team-8_Pre-TST
    - Team-9_Ops
    - Team-10_Willow
    - Team-11_Pondscrum
- name: envToDeploy
  displayName: 'Target Environment to deploy:    (select "development" for Team 1-11)'
  default: development
  type: string
  values:
    - development
    - tst
    - preprod
    - prod
- name: imageTag
  displayName: Enter Tag for the Image (Docker tag) or Release name (Git repo tag)
  default: ''
  type: string

variables:
  - ${{ if eq(parameters.envToDeploy, 'development') }}:
    - name: env
      value: DEV1
    - template: vars/${{ parameters.teamName }}-${{ parameters.envToDeploy }}.yaml
  - ${{ elseif eq(parameters.envToDeploy, 'tst') }}:
    - name: env
      value: TST1
    - template: vars/${{ parameters.envToDeploy }}.yaml
  - ${{ elseif eq(parameters.envToDeploy, 'preprod') }}:
    - name: env
      value: PRE1
    - template: vars/${{ parameters.envToDeploy }}.yaml
  - ${{ elseif eq(parameters.envToDeploy, 'prod') }}:
    - name: env
      value: PRD1
    - template: vars/${{ parameters.envToDeploy }}.yaml
# Release tags reference
  - template: pipelines/image-tags/${{ parameters.envToDeploy }}.yaml@ReleaseTags
  - ${{ if eq(parameters.envToDeploy, 'development') }}:
    - template: pipelines/image-tags/${{ parameters.teamName }}-${{ parameters.envToDeploy }}.yaml@ReleaseTags

resources:
  repositories:
    - repository: CommonTemplates
      name: defra/epr-webapps-code-deploy-templates
      type: github
      ref: main
      endpoint: DEFRA

    # The repo will be reference the repo by a release tag (if the imageTag parameter contains 'release') otherwise it will pull down the main branch.
    - repository: ReleaseTags
      name: RWD-CPR-EPR4P-ADO/epr-app-config-settings
      type: git
      ref: ${{ replace(replace(contains(parameters.imageTag, 'RELEASE'),'True',replace('refs/tags/RELEASETAG','RELEASETAG', parameters.imageTag)),'False','main') }}

extends:
  template: epr-deployment-pipeline.yaml@CommonTemplates
  parameters:
    ${{ if contains(parameters.imageTag, 'RELEASE') }}:
      imageTag: $(DEVRWDWEBWAx410)
    ${{ else }}:
      imageTag: ${{ parameters.imageTag }}
    azureSubscription: $(azureSubscription)
    acrName: $(acr.azureContainerRegistryName)
    registryName: $(acr.repositoryName)
    serviceName: $(serviceName)
    ${{ if eq(parameters.envToDeploy, 'development') }}:
      targetEnvironment: 'development'
    ${{ else }}:
      targetEnvironment: '$(env)'