//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRNPortal.UI.Resources.Views.FileUploadingCompanyDetailsErrors {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUploadCompanyDetailsErrors {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadCompanyDetailsErrors() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PRNPortal.UI.Resources.Views.FileUploadCompanyDetailsErrors.File" +
                            "UploadCompanyDetailsErrors", typeof(FileUploadCompanyDetailsErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string organisation_details {
            get {
                return ResourceManager.GetString("organisation_details", resourceCulture);
            }
        }
        
        internal static string there_are {
            get {
                return ResourceManager.GetString("there_are", resourceCulture);
            }
        }
        
        internal static string in_file {
            get {
                return ResourceManager.GetString("in_file", resourceCulture);
            }
        }
        
        internal static string this_means {
            get {
                return ResourceManager.GetString("this_means", resourceCulture);
            }
        }
        
        internal static string how_to_fix {
            get {
                return ResourceManager.GetString("how_to_fix", resourceCulture);
            }
        }
        
        internal static string download_csv {
            get {
                return ResourceManager.GetString("download_csv", resourceCulture);
            }
        }
        
        internal static string this_will {
            get {
                return ResourceManager.GetString("this_will", resourceCulture);
            }
        }
        
        internal static string use_report {
            get {
                return ResourceManager.GetString("use_report", resourceCulture);
            }
        }
        
        internal static string file_specification {
            get {
                return ResourceManager.GetString("file_specification", resourceCulture);
            }
        }
        
        internal static string upload_again {
            get {
                return ResourceManager.GetString("upload_again", resourceCulture);
            }
        }
        
        internal static string upload_file {
            get {
                return ResourceManager.GetString("upload_file", resourceCulture);
            }
        }
        
        internal static string errors_in_file {
            get {
                return ResourceManager.GetString("errors_in_file", resourceCulture);
            }
        }
    }
}
