variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprprnmanagefrontend'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprprnmanagefrontendrepository'
  serviceName: 'prdrwdwebwa1420'
