//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRNPortal.UI.Resources.Views.SubmissionDeclaration {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUploadSubmissionDeclaration {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadSubmissionDeclaration() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PRNPortal.UI.Resources.Views.FileUploadSubmissionDeclaration.Fil" +
                            "eUploadSubmissionDeclaration", typeof(FileUploadSubmissionDeclaration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string declaration {
            get {
                return ResourceManager.GetString("declaration", resourceCulture);
            }
        }
        
        internal static string by_entering_your_name {
            get {
                return ResourceManager.GetString("by_entering_your_name", resourceCulture);
            }
        }
        
        internal static string you_can_act_on_behalf {
            get {
                return ResourceManager.GetString("you_can_act_on_behalf", resourceCulture);
            }
        }
        
        internal static string the_data_you_are_submitting {
            get {
                return ResourceManager.GetString("the_data_you_are_submitting", resourceCulture);
            }
        }
        
        internal static string enter_your_full_name {
            get {
                return ResourceManager.GetString("enter_your_full_name", resourceCulture);
            }
        }
        
        internal static string org_name_may_face_enforcement_action {
            get {
                return ResourceManager.GetString("org_name_may_face_enforcement_action", resourceCulture);
            }
        }
        
        internal static string submit_file {
            get {
                return ResourceManager.GetString("submit_file", resourceCulture);
            }
        }
        
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
    }
}
