//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRNPortal.UI.Resources.Views.HomePageSelfManaged {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomePageSelfManaged {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageSelfManaged() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PRNPortal.UI.Resources.Views.HomePageSelfManaged.HomePageSelfMan" +
                            "aged", typeof(HomePageSelfManaged).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string report_packaging_data {
            get {
                return ResourceManager.GetString("report_packaging_data", resourceCulture);
            }
        }
        
        internal static string organisation_name {
            get {
                return ResourceManager.GetString("organisation_name", resourceCulture);
            }
        }
        
        internal static string organisation_number_for_x {
            get {
                return ResourceManager.GetString("organisation_number_for_x", resourceCulture);
            }
        }
        
        internal static string compliance_method_title {
            get {
                return ResourceManager.GetString("compliance_method_title", resourceCulture);
            }
        }
        
        internal static string add_compliance_scheme {
            get {
                return ResourceManager.GetString("add_compliance_scheme", resourceCulture);
            }
        }
        
        internal static string self_managed {
            get {
                return ResourceManager.GetString("self_managed", resourceCulture);
            }
        }
    }
}
