//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRNPortal.UI.Resources.Views.FileReUploadConfirmation {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileReUploadCompanyDetailsConfirmation {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileReUploadCompanyDetailsConfirmation() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PRNPortal.UI.Resources.Views.FileReUploadCompanyDetailsConfirmation.FileReUplo" +
                            "adConfirmation", typeof(FileReUploadCompanyDetailsConfirmation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string are_you_sure_you_want_to_replace_the_packaging_data_file_on_your_account {
            get {
                return ResourceManager.GetString("are_you_sure_you_want_to_replace_the_packaging_data_file_on_your_account", resourceCulture);
            }
        }

        internal static string you_can_only_store_one_packaging_data_file_on_your_account {
            get {
                return ResourceManager.GetString("you_can_only_store_one_packaging_data_file_on_your_account", resourceCulture);
            }
        }

        internal static string this_will_not_affect_files_you_have_already_submitted_to_the_regulator {
            get {
                return ResourceManager.GetString("this_will_not_affect_files_you_have_already_submitted_to_the_regulator", resourceCulture);
            }
        }

        internal static string this_is_to_report_packaging_data_for_the_deadline_on_x {
            get {
                return ResourceManager.GetString("this_is_to_report_packaging_data_for_the_deadline_on_x", resourceCulture);
            }
        }

        internal static string current_file_on_account {
            get {
                return ResourceManager.GetString("current_file_on_account", resourceCulture);
            }
        }

        internal static string uploaded_on_x {
            get {
                return ResourceManager.GetString("uploaded_on_x", resourceCulture);
            }
        }
    }
}
